version: '3.8'

services:
  app:
    build: .
    container_name: loan-service
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./file:/app/file
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: loan-service-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata: