// Code generated by MockGen. DO NOT EDIT.
// Source: loan-service/internal/repository/loanapproval (interfaces: ILoanApprovalRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/mock_loan_approval_repository.go -package=mocks loan-service/internal/repository/loanapproval ILoanApprovalRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "loan-service/internal/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockILoanApprovalRepository is a mock of ILoanApprovalRepository interface.
type MockILoanApprovalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockILoanApprovalRepositoryMockRecorder
	isgomock struct{}
}

// MockILoanApprovalRepositoryMockRecorder is the mock recorder for MockILoanApprovalRepository.
type MockILoanApprovalRepositoryMockRecorder struct {
	mock *MockILoanApprovalRepository
}

// NewMockILoanApprovalRepository creates a new mock instance.
func NewMockILoanApprovalRepository(ctrl *gomock.Controller) *MockILoanApprovalRepository {
	mock := &MockILoanApprovalRepository{ctrl: ctrl}
	mock.recorder = &MockILoanApprovalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILoanApprovalRepository) EXPECT() *MockILoanApprovalRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockILoanApprovalRepository) Create(en *entity.LoanApproval) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", en)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockILoanApprovalRepositoryMockRecorder) Create(en any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockILoanApprovalRepository)(nil).Create), en)
}
