// Code generated by MockGen. DO NOT EDIT.
// Source: loan-service/internal/repository/loandisbursement (interfaces: ILoanDisbursementRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/mock_loan_disbursement_repository.go -package=mocks loan-service/internal/repository/loandisbursement ILoanDisbursementRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "loan-service/internal/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockILoanDisbursementRepository is a mock of ILoanDisbursementRepository interface.
type MockILoanDisbursementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockILoanDisbursementRepositoryMockRecorder
	isgomock struct{}
}

// MockILoanDisbursementRepositoryMockRecorder is the mock recorder for MockILoanDisbursementRepository.
type MockILoanDisbursementRepositoryMockRecorder struct {
	mock *MockILoanDisbursementRepository
}

// NewMockILoanDisbursementRepository creates a new mock instance.
func NewMockILoanDisbursementRepository(ctrl *gomock.Controller) *MockILoanDisbursementRepository {
	mock := &MockILoanDisbursementRepository{ctrl: ctrl}
	mock.recorder = &MockILoanDisbursementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILoanDisbursementRepository) EXPECT() *MockILoanDisbursementRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockILoanDisbursementRepository) Create(en *entity.LoanDisbursement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", en)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockILoanDisbursementRepositoryMockRecorder) Create(en any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockILoanDisbursementRepository)(nil).Create), en)
}
