definitions:
  request.ApproveLoan:
    properties:
      fieldOfficerId:
        type: string
      proofOfPicture:
        type: string
    type: object
  request.CreateBorrower:
    properties:
      name:
        type: string
    type: object
  request.DisburseLoan:
    properties:
      borrowerAgreementLetter:
        type: string
      fieldOfficerId:
        type: string
    type: object
  request.InvestLoan:
    properties:
      amount:
        type: integer
    type: object
  request.MockLogin:
    properties:
      email:
        type: string
      role:
        type: string
    type: object
  request.ProposeLoan:
    properties:
      borrowerId:
        type: string
      principalAmount:
        type: integer
      rate:
        type: number
      roi:
        type: number
    type: object
  response.GetBorrower:
    properties:
      createdAt:
        type: string
      createdBy:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  response.GetLoan:
    properties:
      borrowerId:
        type: string
      createdAt:
        type: string
      createdBy:
        type: string
      id:
        type: string
      investedAmount:
        type: integer
      principalAmount:
        type: integer
      rate:
        type: number
      roi:
        type: number
      status:
        type: string
    type: object
  response.GetLoanDetail:
    properties:
      approval:
        $ref: '#/definitions/response.LoanApprovalDetail'
      borrowerId:
        type: string
      createdAt:
        type: string
      createdBy:
        type: string
      disbursement:
        $ref: '#/definitions/response.LoanDisbursementDetail'
      id:
        type: string
      investedAmount:
        type: integer
      investors:
        items:
          $ref: '#/definitions/response.LoanInvestorDetail'
        type: array
      principalAmount:
        type: integer
      rate:
        type: number
      roi:
        type: number
      status:
        type: string
    type: object
  response.GetUser:
    properties:
      email:
        type: string
      role:
        type: string
    type: object
  response.LoanApprovalDetail:
    properties:
      date:
        type: string
      fieldOfficerId:
        type: string
      proofOfPicture:
        type: string
    type: object
  response.LoanDisbursementDetail:
    properties:
      borrowerAgreementLetter:
        type: string
      date:
        type: string
      fieldOfficerId:
        type: string
    type: object
  response.LoanInvestorDetail:
    properties:
      amount:
        type: integer
      id:
        type: string
    type: object
  response.UploadBorrowerLetter:
    properties:
      id:
        type: string
      name:
        type: string
      type:
        type: string
    type: object
  response.UploadLoanProofOfPicture:
    properties:
      id:
        type: string
      name:
        type: string
      type:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/mock-login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.MockLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      summary: Mock login using email and user role
      tags:
      - Auth
  /api/v1/auth/user:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.GetUser'
            type: array
      summary: Get all users for testing purpose
      tags:
      - Auth
  /api/v1/borrower:
    get:
      consumes:
      - application/json
      parameters:
      - description: default is 1
        in: query
        name: page
        type: integer
      - description: default is 10
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.GetBorrower'
            type: array
      summary: Get list of borrowers
      tags:
      - Borrower
    post:
      consumes:
      - application/json
      description: Borrower can only be created by user with fieldOfficer role
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.CreateBorrower'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create borrower
      tags:
      - Borrower
  /api/v1/borrower/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Borrower ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      summary: Delete borrower by ID
      tags:
      - Borrower
  /api/v1/file/{id}/_download:
    post:
      parameters:
      - description: File ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: Download file
      tags:
      - File
  /api/v1/loan:
    get:
      consumes:
      - application/json
      parameters:
      - description: default is 1
        in: query
        name: page
        type: integer
      - description: default is 10
        in: query
        name: size
        type: integer
      - description: filter by loan status
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.GetLoan'
            type: array
      summary: Get list of loans
      tags:
      - Loan
    post:
      consumes:
      - application/json
      description: User with role fieldOfficer can propose a loan for a borrower
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.ProposeLoan'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Propose loan by field officer
      tags:
      - Loan
  /api/v1/loan/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Loan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetLoanDetail'
      summary: Get loan detail
      tags:
      - Loan
  /api/v1/loan/{id}/_approve:
    post:
      consumes:
      - application/json
      description: User with role internal can approve a loan. fieldOfficerId is user's
        email, proofOfPicture is file id got from upload response
      parameters:
      - description: Loan ID
        in: path
        name: id
        required: true
        type: string
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.ApproveLoan'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      summary: Approve loan by internal
      tags:
      - Loan
  /api/v1/loan/{id}/_disburse:
    post:
      consumes:
      - application/json
      description: User with role internal can approve a loan. fieldOfficerId is user's
        email, borrowerAgreementLetter is file id got from upload response
      parameters:
      - description: Loan ID
        in: path
        name: id
        required: true
        type: string
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.DisburseLoan'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      summary: Diburse loan by internal
      tags:
      - Loan
  /api/v1/loan/{id}/_invest:
    post:
      consumes:
      - application/json
      parameters:
      - description: Loan ID
        in: path
        name: id
        required: true
        type: string
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.InvestLoan'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      summary: Invest loan by investor
      tags:
      - Loan
  /api/v1/loan/{id}/borrower-agreement-letter:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Loan ID
        in: path
        name: id
        required: true
        type: string
      - description: PDF to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UploadBorrowerLetter'
      summary: Upload borrower agreement letter
      tags:
      - Loan
  /api/v1/loan/{id}/proof:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Loan ID
        in: path
        name: id
        required: true
        type: string
      - description: Picture to upload
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UploadLoanProofOfPicture'
      summary: Upload loan proof of picture
      tags:
      - Loan
swagger: "2.0"
