definitions:
  request.CreateBorrower:
    properties:
      name:
        type: string
    type: object
  response.GetBorrower:
    properties:
      createdAt:
        type: string
      createdBy:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/borrower:
    get:
      consumes:
      - application/json
      parameters:
      - description: default is 1
        in: query
        name: page
        type: integer
      - description: default is 10
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.GetBorrower'
            type: array
      summary: Get list of borrowers
      tags:
      - Borrower
    post:
      consumes:
      - application/json
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.CreateBorrower'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create borrower
      tags:
      - Borrower
  /api/v1/borrower/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Borrower ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      summary: Delete borrower by ID
      tags:
      - Borrower
swagger: "2.0"
